---
- hosts: blog_nodes
  become: yes
  vars:
    WP_URL: https://wordpress.org/latest.tar.gz
    EPEL_REPO_URL: https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
    REMI_REPO_URL: https://rpms.remirepo.net/enterprise/remi-release-7.rpm
    DB_NAME: blog
    DB_USER: blog
    DB_PWD: blog
  tasks:
    - name: "Install apache server"
      yum:
        name: httpd
        state: present
    - name: "Put apache config to etc"
      copy:
        src: files/httpd-vhost.conf
        dest: /etc/httpd/conf.d/blog.conf
    - name: "Extract WP installation"
      unarchive:
        src: "{{ WP_URL }}"
        dest: /var/www
        remote_src: yes
    - name: "Install EPEL repo"
      yum:
        name: "{{ EPEL_REPO_URL }}"
        state: present
    - name: "Install PHP repo"
      yum:
        name: "{{ REMI_REPO_URL }}"
        state: present
    - name: "Install PHP packages"
      yum:
        name: 
          - php80 
          - php80-php 
          - php-mysqlnd 
          - php80-php-pecl-mysql
        state: present
    - name: "Add MariaDB repo config to yum config"
      copy:
        src: files/mariadb.repo
        dest: /etc/yum.repos.d/Mariadb.repo
    - name: "Install MariaDB server"
      yum:
        name:
          - MariaDB-server
          - MariaDB-client
          - MySQL-python
    - name: "Start MariaDB"
      service:
        name: mariadb
        state: started
        enabled: yes
    - name: "Create DB"
      mysql_db:
        name: "{{ DB_NAME }}"
        state: present
    - name: "Create user and grant privileges"
      mysql_user:
        name: "{{ DB_USER }}"
        password: "{{ DB_PWD }}"
        priv: "{{ DB_NAME }}.*:ALL"
        state: present
    - name: "Put wp config and populate with envs"
      template:
        src: files/wp-config.php
        dest: /var/www/wordpress/wp-config.php
    - name: "Restart apache server"
      service:
        name: httpd
        state: restarted
        enabled: yes 